# Generated by Django 4.2.3 on 2023-08-10 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
