# Generated by Django 4.2.3 on 2023-08-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('nutrient1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction1', to='supplements.nutrient')),
                ('nutrient2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction2', to='supplements.nutrient')),
            ],
        ),
    ]
