# Generated by Django 4.2.3 on 2023-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendednutrient',
            name='limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
