# Generated by Django 4.2.3 on 2023-08-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0004_alter_interaction_nutrient1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='nutrient1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_nutrient1', to='supplements.nutrient'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='nutrient2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_nutrient2', to='supplements.nutrient'),
        ),
    ]
