# Generated by Django 4.2.3 on 2023-08-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersupplementintake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSupplementIntake',
        ),
    ]
