# Generated by Django 4.2.3 on 2023-08-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남', '남성'), ('여', '여성')], max_length=1),
        ),
    ]
